---
- name: Install Java, Python 3, and Jenkins
  hosts: localhost  # Replace with the target host(s) where you want to install the software
  become: yes

  tasks:
    - name: Install Java
      apt:
        name: openjdk-11-jdk  # Adjust the package name for the Java version you want to install
        state: present

    - name: Install Python 3
      apt:
        name: python3
        state: present

    - name: Install Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
