---
- hosts: localhost

  tasks:
  -  name: Retrieve Jenkins GPG key
     get_url:
        url: "https://pkg.jenkins.io/debian/jenkins.io-2023.key"
        dest: "/tmp/jenkins.io-2023.key"
        mode: "0644"
  -  name: Import Jenkins GPG key
     apt_key:
        data: "{{ lookup('file', '/tmp/jenkins.io-2023.key') }}"
        state: present
  -  name: Add Jenkins Debian Repository
     lineinfile:
        path: /etc/apt/sources.list.d/jenkins.list
        line: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
        create: yes
        owner: root
        group: root
        mode: "0644"
  -  name: Update apt cache (for Debian-based systems)
     apt:
        update_cache: yes
     become: yes
  -  name: install
     apt: name=jenkins 
     become: yes
     
